# Generated by Django 4.2.11 on 2024-04-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
